import { ORDER_STATUS } from "../constants/orderStatus.js";

export const allowedStatusTransitions = {
  [ORDER_STATUS.PENDING]: [
    ORDER_STATUS.PICKUP_ASSIGNED,
    ORDER_STATUS.CANCELLED,
  ],

  [ORDER_STATUS.PICKUP_ASSIGNED]: [
    ORDER_STATUS.PICKED_UP,
    ORDER_STATUS.CANCELLED,
  ],

  [ORDER_STATUS.PICKED_UP]: [ORDER_STATUS.PROCESSING],

  [ORDER_STATUS.PROCESSING]: [ORDER_STATUS.READY_FOR_DELIVERY],

  [ORDER_STATUS.READY_FOR_DELIVERY]: [ORDER_STATUS.OUT_FOR_DELIVERY],

  [ORDER_STATUS.OUT_FOR_DELIVERY]: [ORDER_STATUS.DELIVERED],

  [ORDER_STATUS.DELIVERED]: [],

  [ORDER_STATUS.CANCELLED]: [],
};
